apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 7777
      targetPort: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bojanivanovski/finki-totp-backend
          ports:
            - containerPort: 7777
          envFrom:
            - secretRef:
                name: finki-totp-secrets
            - configMapRef:
                name: finki-totp-config-maps
